backend:
  image:
    repository: ghcr.io/juliauu/wuda/backend
    tag: local
  replicaCount: 1
  service:
    port: 5000
    targetPort: 5000
    type: NodePort
  POSTGRES_DB: games
  POSTGRES_USER: board_games
  POSTGRES_PASSWORD: alamakota
  POSTGRES_HOST: postgres
  JWT_KEY: your_jwt_key_here
  APP_HOST: 0.0.0.0
  APP_PORT: 5000

frontend:
  image:
    repository: ghcr.io/juliauu/wuda/frontend
    tag: latest
  replicaCount: 1
  service:
    port: 80
    targetPort: 8000
    type: NodePort
  SECRET_KEY: your_secret_key_here
  BACKEND_HOSTNAME: backend
  APP_HOST: 0.0.0.0
  APP_PORT: 8000

database:
  enabled: true
  image:
    repository: postgres
    tag: latest
  replicaCount: 1
  name: games
  user: board_games
  password: alamakota
  service:
    port: 5432
    targetPort: 5432
    type: ClusterIP